///////////////////////////////////////////////////////////////////////////////
//                              CUSTOM ADDONS
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Weapons
///////////////////////////////////////////////////////////////////////////////

hlc_rifle_l1a1slr
hlc_rifle_SLR
hlc_rifle_STG58F
hlc_rifle_FAL5061
hlc_rifle_c1A1
hlc_rifle_LAR
hlc_rifle_SLRchopmod
hlc_rifle_falosw
hlc_rifle_osw_GL
hlc_rifle_g3sg1
hlc_rifle_psg1
hlc_rifle_g3a3
hlc_rifle_g3ka4
HLC_Rifle_g3ka4_GL
hlc_rifle_hk51
hlc_rifle_hk53
hlc_rifle_M14
hlc_rifle_M21
hlc_rifle_M14DMR
hlc_rifle_m14sopmod

hlc_lmg_minimipara
hlc_lmg_minimi
hlc_lmg_minimi_railed
hlc_lmg_m249para
hlc_lmg_M249E2
hlc_m249_pip1
hlc_m249_pip2
hlc_m249_pip3
hlc_m249_pip4

hlc_rifle_ak74
hlc_rifle_aks74
hlc_rifle_aks74u
hlc_rifle_ak47
hlc_rifle_akm
hlc_rifle_rpk
hlc_rifle_ak12
hlc_rifle_akmgl
hlc_rifle_aks74_GL
hlc_rifle_RU556
hlc_rifle_RU5562
hlc_rifle_Colt727
hlc_rifle_Colt727_GL
hlc_rifle_bcmjack
hlc_rifle_Bushmaster300
hlc_rifle_vendimus
hlc_rifle_SAMR
hlc_rifle_honeybase
hlc_rifle_honeybadger

hlc_smg_mp5a2
hlc_smg_mp5a3
hlc_smg_mp5a4
hlc_smg_mp5n
hlc_smg_mp510
hlc_smg_mp5sd5
hlc_smg_mp5sd6
hlc_smg_9mmar

hlc_rifle_awcovert
hlc_rifle_awcovert_BL
hlc_rifle_awcovert_FDE
hlc_rifle_awmagnum
hlc_rifle_awmagnum_BL
hlc_rifle_awmagnum_FDE
hlc_rifle_awMagnum_FDE_ghillie
hlc_rifle_awMagnum_BL_ghillie
hlc_rifle_awMagnum_OD_ghillie

RH_m4
RH_m4_tg
RH_m4_des
RH_m4_wdl
RH_m4_ris
RH_m4a1_ris
RH_m4a1_ris_tg
RH_m4a1_ris_des
RH_m4a1_ris_wdl
RH_m4_ris_m_tg
RH_m4_ris_m_des
RH_m4_ris_m_wdl
RH_m4a6_tg
RH_m4a6_des
RH_m4a6_wdl
RH_m4sbr
RH_m4sbr_g
RH_m4sbr_b
RH_m16a1
RH_m16a2
RH_m16a3
RH_m16a4
RH_m16a4_tg
RH_m16a4_des
RH_m16a4_wdl
RH_m16a4_m
RH_m16a4_m_tg
RH_m16a4_m_des
RH_m16a4_m_wdl
RH_m4m
RH_m4m_g
RH_m4m_b
RH_m4_moe
RH_m4_moe_g
RH_m4_moe_b
RH_m4a6
RH_m16a6
RH_m16a6_tg
RH_m16a6_des
RH_m16a6_wdl
RH_sbr9
RH_sbr9_tg
RH_sbr9_des
RH_sbr9_wdl
RH_mk12mod1
RH_Mk12mod1_tg
RH_Mk12mod1_des
RH_Mk12mod1_wdl
RH_samr
RH_SAMR_tg
RH_SAMR_des
RH_SAMR_wdl
RH_hb
RH_hb_b
RH_hk416
RH_hk416_tg
RH_hk416_des
RH_hk416_wdl
RH_hk416c
RH_hk416c_tg
RH_hk416c_des
RH_hk416c_wdl
RH_hk416s
RH_hk416s_tg
RH_hk416s_des
RH_hk416s_wdl
RH_m27iar
RH_m27iar_tg
RH_m27iar_des
RH_m27iar_wdl
RH_ar10
RH_mk11
RH_m110
RH_sr25ec

RH_deagle
RH_deagleg
RH_deagles
RH_deaglem
RH_cz75
RH_sw659
RH_usp
RH_mak
RH_m1911
RH_kimber
RH_kimber_nw
RH_uspm
RH_m9
RH_m9c
RH_vz61
RH_g18
RH_g17
RH_tt33
RH_mk2
RH_p226
RH_p226s
RH_g19
RH_g19t
RH_vp70
RH_mateba
RH_python
RH_mp412
RH_bull
RH_bullb
RH_ttracker
RH_ttracker_g
RH_fnp45
RH_fnp45t
RH_fn57
RH_fn57_g
RH_fn57_t
RH_gsh18
RH_tec9
RH_muzi

rhs_weap_m240B
rhs_weap_m249_pip
rhs_weap_pkm
rhs_weap_pkp
rhs_weap_ak103
rhs_weap_ak103_npz
rhs_weap_ak103_1
rhs_weap_ak103_2
rhs_weap_ak74m
rhs_weap_ak74m_plummag
rhs_weap_ak74m_npz
rhs_weap_ak74m_folded
rhs_weap_ak74m_camo
rhs_weap_ak74m_desert
rhs_weap_ak74m_2mag
rhs_weap_ak74m_2mag_npz
rhs_weap_ak74m_2mag_camo
rhs_weap_ak74m_gp25
rhs_weap_ak74m_gp25_npz
rhs_weap_akm
rhs_weap_akms
rhs_weap_m4
rhs_weap_m4_grip
rhs_weap_m4_grip2
rhs_weap_m4_bipod
rhs_weap_m4_carryhandle
rhs_weap_m4_carryhandle_pmag
rhs_weap_m4_m203
rhs_weap_m4_m203S
rhs_m4_m320
rhs_weap_m4a1
rhs_weap_m4a1_grip
rhs_weap_m4a1_grip2
rhs_weap_m4a1_bipod
rhs_weap_m4a1_carryhandle
rhs_weap_m4a1_carryhandle_grip
rhs_weap_m4a1_carryhandle_grip2
rhs_weap_m4a1_carryhandle_bipod
rhs_weap_m4a1_m203
rhs_weap_m4a1_m203s
rhs_weap_m4a1_carryhandle_m203
rhs_m4a1_m320
rhs_weap_m4a1_blockII
rhs_weap_m4a1_blockII_grip2
rhs_weap_m4a1_blockII_KAC
rhs_weap_m4a1_blockII_grip2_KAC
rhs_weap_m4a1_blockII_M203
rhs_weap_m16a4
rhs_weap_m16a4_bipod
rhs_weap_m16a4_grip
rhs_weap_m16a4_carryhandle
rhs_weap_m16a4_carryhandle_pmag
rhs_weap_m16a4_carryhandle_M203
rhs_weap_m14ebrri
rhs_weap_mk18
rhs_weap_mk18_grip2
rhs_weap_mk18_KAC
rhs_weap_mk18_grip2_KAC
rhs_weap_XM2010
rhs_weap_XM2010_wd
rhs_weap_XM2010_d
rhs_weap_XM2010_sa
rhs_weap_sr25
rhs_weap_sr25_ec
rhs_weap_svdp
rhs_weap_svdp_wd
rhs_weap_svds
rhs_weap_svdp_npz
rhs_weap_svdp_wd_npz
rhs_weap_svds_npz

rhs_weap_M136
rhs_weap_M136_hedp
rhs_weap_M136_hp



//Not included on purpose, uncomment if you want added to the shop
// These are going to be able to be found only at military bases
/*
RH_m4_m203
RH_m4_m203_tg
RH_m4_m203_des
RH_m4_m203_wdl
RH_m4_ris_m203
RH_m4_ris_m203s
RH_m4a1_ris_m203
RH_m4a1_ris_m203_tg
RH_m4a1_ris_m203_des
RH_m4a1_ris_m203_wdl
RH_m4a1_ris_m203s
RH_m4a1_ris_m203s_tg
RH_m4a1_ris_m203s_des
RH_m4a1_ris_m203s_wdl
RH_m16a1gl
RH_m16a2gl
RH_m16a4gl
RH_m16a4gl_tg
RH_m16a4gl_des
RH_m16a4gl_wdl
*/

///////////////////////////////////////////////////////////////////////////////
// Ammo
///////////////////////////////////////////////////////////////////////////////

hlc_20Rnd_762x51_B_G3
hlc_20rnd_762x51_T_G3
hlc_50rnd_762x51_M_G3
hlc_20Rnd_762x51_B_M14
hlc_20rnd_762x51_T_M14
hlc_50rnd_762x51_M_M14
hlc_20Rnd_762x51_B_fal
hlc_20Rnd_762x51_t_fal
hlc_20Rnd_762x51_S_fal
hlc_50rnd_762x51_M_FAL

hlc_200rnd_556x45_M_SAW
hlc_200rnd_556x45_T_SAW
hlc_200rnd_556x45_B_SAW

29rnd_300BLK_STANAG
29rnd_300BLK_STANAG_T
29rnd_300BLK_STANAG_S
hlc_30rnd_556x45_EPR
hlc_30rnd_556x45_SOST
hlc_30rnd_556x45_SPR
hlc_30Rnd_545x39_B_AK
hlc_30Rnd_545x39_T_AK
hlc_30Rnd_545x39_EP_AK
hlc_45Rnd_545x39_t_rpk
hlc_30Rnd_762x39_b_ak
hlc_30Rnd_762x39_t_ak
hlc_45Rnd_762x39_t_rpk
hlc_45Rnd_762x39_m_rpk

hlc_VOG25_AK
hlc_GRD_White
hlc_GRD_red
hlc_GRD_green
hlc_GRD_blue
hlc_GRD_orange
hlc_GRD_purple
rhs_mag_rgd5
rhs_mag_nspd
rhs_mag_fakel
rhs_mag_fakels
rhs_mag_zarya2
rhs_mag_plamyam

hlc_30Rnd_9x19_B_MP5
hlc_30Rnd_9x19_GD_MP5
hlc_30Rnd_9x19_SD_MP5
hlc_30Rnd_10mm_B_MP5
hlc_30Rnd_10mm_JHP_MP5

hlc_5rnd_300WM_FMJ_AWM
hlc_5rnd_300WM_AP_AWM
hlc_5rnd_300WM_BTSP_AWM
hlc_5rnd_300WM_mk248_AWM
hlc_5rnd_300WM_SBT_AWM

RH_30Rnd_556x45_M855A1
RH_30Rnd_556x45_Mk262
RH_30Rnd_556x45_Mk318
RH_20Rnd_556x45_M855A1
RH_20Rnd_556x45_Mk262
RH_20Rnd_556x45_Mk318
RH_60Rnd_556x45_M855A1
RH_60Rnd_556x45_Mk262
RH_60Rnd_556x45_Mk318

RH_30Rnd_68x43_FMJ
RH_30Rnd_68x43_Match
RH_30Rnd_762x35_FMJ
RH_30Rnd_762x35_Match
RH_30Rnd_762x35_MSB

RH_20Rnd_762x51_M80A1
RH_20Rnd_762x51_Mk316LR
RH_20Rnd_762x51_Mk319
RH_20Rnd_762x51_LFMJSB
RH_20Rnd_762x51_AR10

RH_32Rnd_9mm_M822
RH_32Rnd_9mm_HP
RH_32Rnd_9mm_HPSB

RH_7Rnd_50_AE
RH_16Rnd_9x19_cz
RH_14Rnd_9x19_sw
RH_12Rnd_45cal_usp
RH_8Rnd_9x18_Mak
RH_7Rnd_45cal_m1911
RH_16Rnd_40cal_usp
RH_15Rnd_9x19_M9
RH_20Rnd_32cal_vz61
RH_33Rnd_9x19_g18
RH_17Rnd_9x19_g17
RH_8Rnd_762_tt33
RH_10Rnd_22LR_mk2
RH_15Rnd_9x19_SIG
RH_18Rnd_9x19_VP
RH_6Rnd_44_Mag
RH_6Rnd_357_Mag
RH_6Rnd_454_Mag
RH_6Rnd_45ACP_Mag
RH_15Rnd_45cal_fnp
RH_20Rnd_57x28_FN
RH_18Rnd_9x19_gsh
RH_32Rnd_9x19_tec
RH_30Rnd_9x19_UZI

rhs_30Rnd_762x39mm
rhs_30Rnd_762x39mm_tracer
rhs_30Rnd_762x39mm_89
rhs_30Rnd_545x39_AK
rhs_30Rnd_545x39_AK_green
rhs_30Rnd_545x39_7n10_AK
rhs_30Rnd_545x39_7n22_AK
rhs_45Rnd_545X39_AK
rhs_45Rnd_545X39_7N10_AK
rhs_45Rnd_545X39_7N22_AK
rhs_100Rnd_762x54mmR
rhs_100Rnd_762x54mmR_green
rhs_10Rnd_762x54mmR_7N1
rhs_mag_9x19_17
rhsusf_mag_7x45acp_MHP
rhs_mag_30Rnd_556x45_Mk262_Stanag
rhs_mag_30Rnd_556x45_M855A1_Stanag
rhs_mag_30Rnd_556x45_M855A1_Stanag_No_Tracer
rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red
rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Green
rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Yellow
rhsusf_20Rnd_762x51_m993_Mag
rhsusf_5Rnd_300winmag_xm2010
rhsusf_20Rnd_762x51_m118_special_Mag
rhs_200rnd_556x45_B_SAW
rhs_200rnd_556x45_T_SAW
rhs_200rnd_556x45_M_SAW
rhs_100Rnd_556x45_soft_pouch
rhs_100Rnd_556x45_M200_soft_pouch
rhs_200Rnd_556x45_soft_pouch
rhsusf_100Rnd_762x51
rhsusf_100Rnd_762x51_m80a1epr
rhsusf_100Rnd_762x51_m993

//Make expensive
rhs_m136_mag
rhs_m136_hedp_mag
rhs_m136_hp_mag



///////////////////////////////////////////////////////////////////////////////
// optic
///////////////////////////////////////////////////////////////////////////////

RH_eotech553
RH_eotech553mag
RH_eotech553_tan
RH_eotech553mag_tan
RH_eotexps3
RH_eotexps3_tan
RH_eothhs1
RH_eothhs1_tan
RH_compm4s
RH_compm2
RH_compm2l
RH_compm2_tan
RH_compm2l_tan
RH_t1
RH_t1_tan
RH_reflex
RH_shortdot
RH_m3lr
RH_ta01nsn
RH_ta01nsn_2D
RH_ta31rco
RH_ta31rco_2D
RH_ta31rmr
RH_ta31rmr_2D
RH_ta01nsn_tan
RH_ta01nsn_tan_2D
RH_ta31rco_tan
RH_ta31rco_tan_2D
RH_ta31rmr_tan
RH_ta31rmr_tan_2D
RH_ta648
RH_accupoint
RH_leu_mk4
RH_c79
RH_c79_2D
RH_m145
RH_barska_rds
RH_cmore
RH_LTdocter
RH_LTdocterl
RH_zpoint

hlc_optic_artel_m14
hlc_optic_LRT_m14
hlc_optic_suit
HLC_Optic_ZFSG1
hlc_optic_accupoint_g3
HLC_Optic_PSO1
HLC_Optic_1p29
hlc_optic_kobra

rhsusf_acc_harris_bipod
rhsusf_acc_EOTECH
rhsusf_acc_eotech_552
rhsusf_acc_LEUPOLDMK4
rhsusf_acc_LEUPOLDMK4_2
rhsusf_acc_ELCAN
rhsusf_acc_ELCAN_PIP
rhsusf_acc_ACOG
rhsusf_acc_ACOG2
rhsusf_acc_ACOG3
rhsusf_acc_ACOG_USMC
rhsusf_acc_ACOG2_USMC
rhsusf_acc_ACOG3_USMC
rhsusf_acc_compm4
rhs_acc_tgpa
rhs_acc_1p29
rhs_acc_1p63
rhs_acc_1pn93_1
rhs_acc_1pn93_2
rhs_acc_ekp1
rhs_acc_pgo7v
rhs_acc_pkas
rhs_acc_pso1m2

///////////////////////////////////////////////////////////////////////////////
// Attachments
///////////////////////////////////////////////////////////////////////////////

RH_peq15
RH_peq15_top
RH_peq15b
RH_peq15b_top
RH_peq2
RH_peq2_top
RH_SFM952V
RH_SFM952V_tan

RH_qdss_nt4
RH_qdss_nt4_tg
RH_qdss_nt4_des
RH_qdss_nt4_wdl
RH_saker
RH_saker_tg
RH_saker_des
RH_saker_wdl
RH_Saker762
RH_Saker762_tg
RH_Saker762_des
RH_Saker762_wdl
RH_fa556
RH_fa556_tg
RH_fa556_des
RH_fa556_wdl
RH_fa762
RH_fa762_tg
RH_fa762_des
RH_fa762_wdl
RH_spr_mbs
RH_spr_mbs_tg
RH_spr_mbs_des
RH_spr_mbs_wdl
RH_tundra
RH_tundra_tg
RH_tundra_des
RH_tundra_wdl
RH_m110sd
RH_m110sd_t
RH_HBLM
RH_HBLM_tg
RH_HBLM_des
RH_HBLM_wdl
RH_TD_ACB
RH_TD_ACB_g
RH_TD_ACB_b
hlc_muzzle_snds_HK33
hlc_muzzle_snds_G3
hlc_muzzle_snds_M14
hlc_muzzle_snds_fal
hlc_muzzle_545SUP_AK
hlc_muzzle_762SUP_AK
hlc_muzzle_556NATO_KAC
hlc_muzzle_300blk_KAC
hlc_muzzle_snds_AUG
hlc_muzzle_snds_a6AUG
hlc_muzzle_Agendasix
hlc_muzzle_Tundra
hlc_muzzle_Agendasix10mm
RH_demz
RH_gemtech9
RH_A26
RH_suppr9
RH_aacusp
RH_gemtech45
RH_osprey
RH_fhusp
RH_x2
RH_m6x
RH_x300
RH_pmsd
RH_pmir
RH_matchsd
RH_m9qd
RH_vp70stock
RH_docter
RH_sfn57
RH_tecsd
RH_muzisd
rhsusf_acc_anpeq15
rhsusf_acc_anpeq15A
rhsusf_acc_anpeq15_light
rhsusf_acc_M2010S
rhsusf_acc_rotex5_grey
rhsusf_acc_rotex5_tan
rhsusf_acc_nt4_black
rhsusf_acc_nt4_tan
rhsusf_acc_SF3P556
rhsusf_acc_SFMB556
rhsusf_acc_SR25S

///////////////////////////////////////////////////////////////////////////////
// Clothing
///////////////////////////////////////////////////////////////////////////////

FUTARM_CombatUniform_mcam
FUTARM_CombatUniform_Tee
FUTARM_CombatUniform_Full
U_PMC_GTShirt_DJeans
U_PMC_GTShirt_SJeans
U_PMC_BlkTShirt_DJeans
U_PMC_BlkTShirt_SJeans
U_PMC_BluTShirt_SJeans
U_PMC_WTShirt_DJeans
U_PMC_BluePlaidShirt_BeigeCords
U_PMC_RedPlaidShirt_DenimCords
U_PMC_BlackPoloShirt_BeigeCords
U_PMC_BluPolo_BgPants
U_PMC_BgPolo_GrnPants
U_PMC_BlckPolo_BgPants
U_PMC_BlckPolo_BluPants
U_PMC_BluPolo_GrnPants
U_PMC_BrnPolo_BgPants
U_PMC_BrnPolo_BluPants
U_PMC_GrnPolo_BgPants
U_PMC_WhtPolo_BgPants
U_PMC_WhtPolo_BluPants
U_PMC_WhtPolo_GrnPants
U_PMC_CombatUniformRS_BSGPBB
U_PMC_CombatUniformRS_BSGPSB
U_PMC_CombatUniformRS_BSSPBB
U_PMC_CombatUniformRS_BSSPSB
U_PMC_CombatUniformRS_GSBPBB
U_PMC_CombatUniformRS_GSSPBB
U_PMC_CombatUniformRS_IndPBSBB
U_PMC_CombatUniformRS_SSBPBB
U_PMC_CombatUniformRS_SSGPBB
U_PMC_CombatUniformRS_SSGPSB
U_PMC_CombatUniformRS_ChckDBS_GPSB
U_PMC_CombatUniformRS_ChckLB_GPBB
U_PMC_CombatUniformRS_ChckLR_SPBB
U_PMC_CombatUniformRS_ChckP_BPBB
U_PMC_CombatUniformLS_BSGPBB
U_PMC_CombatUniformLS_BSGPSB
U_PMC_CombatUniformLS_BSSPBB
U_PMC_CombatUniformLS_BSSPSB
U_PMC_CombatUniformLS_GSBPBB
U_PMC_CombatUniformLS_GSSPBB
U_PMC_CombatUniformLS_IndPBSBB
U_PMC_CombatUniformLS_SSBPBB
U_PMC_CombatUniformLS_SSGPBB
U_PMC_CombatUniformLS_SSGPSB
U_PMC_CombatUniformLS_ChckDBS_GPSB
U_PMC_CombatUniformLS_ChckLB_GPBB
U_PMC_CombatUniformLS_ChckLR_SPBB
U_PMC_CombatUniformLS_ChckP_BPBB
tfa_coverall_black_co
tfa_coverall_tan_co
tfa_c_acu
tfa_c_atac_au
tfa_c_atac_fg
tfa_c_bdu
tfa_c_bdu_blk
tfa_c_bdu_grn
tfa_c_bdu_khk
tfa_c_bdu_mcam
tfa_c_bdu_nwu2
tfa_c_bdu_nwu3
tfa_c_bdu_tiger
tfa_c_bdu_tri
tfa_c_dou
tfa_c_dou_bdu
tfa_c_dou_grn
tfa_c_dou_nwu3
tfa_c_dou_white
tfa_c_khk_bdu
tfa_c_kryptek_high
tfa_c_kryptek_man
tfa_c_kryptek_nom
tfa_c_mcam
tfa_c_mcam_bdu
tfa_c_mcam_blk
tfa_c_mcam_grn
tfa_c_mcam_khk
tfa_c_mcam_nwu2
tfa_c_mcam_nwu3
tfa_c_mcam_tiger
tfa_c_mcam_tri
tfa_c_nwu2
tfa_c_nwu2_bdu
tfa_c_nwu2_blk
tfa_c_nwu2_grn
tfa_c_nwu2_khk
tfa_c_nwu2_mcam
tfa_c_nwu2_nwu3
tfa_c_nwu2_tiger
tfa_c_nwu2_tri
tfa_c_nwu3
tfa_c_nwu3_bdu
tfa_c_nwu3_blk
tfa_c_nwu3_grn
tfa_c_nwu3_khk
tfa_c_nwu3_mcam
tfa_c_nwu3_nwu2
tfa_c_nwu3_tiger
tfa_c_nwu3_tri
tfa_c_tiger
tfa_c_tiger_bdu
tfa_c_tiger_blk
tfa_c_tiger_grn
tfa_c_tiger_khk
tfa_c_tiger_mcam
tfa_c_tiger_nwu2
tfa_c_tiger_nwu3
tfa_c_tiger_tri
tfa_c_tri
tfa_c_tri_bdu
tfa_c_tri_blk
tfa_c_tri_grn
tfa_c_tri_khk
tfa_c_tri_mcam
tfa_c_tri_nwu2
tfa_c_tri_nwu3
tfa_c_tri_tiger
tfa_c_usmc_des
tfa_c_usmc_wdl
tfa_c_white
tfa_c_white_bdu
tfa_c_white_dou
tfa_coverall_black_co
tfa_coverall_tan_co
tfa_inst2_tan_co
tfa_inst2_wdl_co
tfa_inst_co
tfa_inst_tan_co
tfa_inst_wdl_co
tfa_s_blk
tfa_s_blk_bdu
tfa_s_blk_grn
tfa_s_blk_khk
tfa_s_blk_mcam
tfa_s_blk_nwu2
tfa_s_blk_nwu3
tfa_s_blk_tiger
tfa_s_blk_tri
tfa_s_grn
tfa_s_grn_bdu
tfa_s_grn_blk
tfa_s_grn_khk
tfa_s_grn_mcam
tfa_s_grn_nwu2
tfa_s_grn_nwu3
tfa_s_grn_tiger
tfa_s_grn_tri
tfa_s_khk
tfa_s_khk_bdu
tfa_s_khk_blk
tfa_s_khk_grn
tfa_s_khk_mcam
tfa_s_khk_nwu2
tfa_s_khk_nwu3
tfa_s_khk_tiger
tfa_s_khk_tri
tfa_s_white_nwu3
tfa_atac_au
tfa_atac_fg
tfa_aus_des
tfa_aus_wdl
tfa_bel_des
tfa_bel_wdl
tfa_can_des
tfa_can_wdl
tfa_den_des
tfa_den_wdl
tfa_fin_des
tfa_fin_wdl
tfa_fra_cce
tfa_fra_dag
tfa_ger_des
tfa_ger_wdl
tfa_ita_des
tfa_ita_wdl
tfa_jpn_des
tfa_jpn_wdl
tfa_mcam
tfa_ned_des
tfa_ned_wdl
tfa_nor_des
tfa_nor_wdl
tfa_nvg_co
tfa_pol_des
tfa_pol_wdl
tfa_swe_des
tfa_swe_wdl
tfa_tri
tfa_uk_des
tfa_uk_mtp
tfa_uk_wdl
tfa_us_des
tfa_us_tiger
tfa_wood
rhs_uniform_cu_ocp
rhs_uniform_cu_ucp
rhs_uniform_cu_ocp_1stcav
rhs_uniform_cu_ucp_1stcav
rhs_uniform_cu_ocp_82nd
rhs_uniform_cu_ucp_82nd
rhs_uniform_cu_ocp_101st
rhs_uniform_cu_ucp_101st
rhs_uniform_cu_ocp_10th
rhs_uniform_cu_ucp_10th
rhs_uniform_cu_ucp_patchless
rhs_uniform_cu_ocp_patchless
rhs_uniform_FROG01_d
rhs_uniform_FROG01_wd
rhs_uniform_FROG01_m81
rhs_uniform_flora
rhs_uniform_df15
rhs_uniform_vdv_emr
rhs_uniform_msv_emr
rhs_uniform_vdv_flora
rhs_uniform_vdv_mflora
rhs_uniform_mflora_patchless
rhs_uniform_flora_patchless
rhs_uniform_flora_patchless_alt
rhs_uniform_emr_patchless
rhs_uniform_m88_patchless
rhs_uniform_gorka_r

///////////////////////////////////////////////////////////////////////////////
// Backpacks
///////////////////////////////////////////////////////////////////////////////

FUTARM_Kitbag
FUTARM_Kitbag_AT
FUTARM_Kitbag_MED
FUTARM_Kitbag_ENG
tfa_assault_acu
tfa_assault_blk
tfa_assault_dou
tfa_assault_fol
tfa_assault_mcam
tfa_assault_nwu2
tfa_assault_tan
tfa_assault_wte
tfa_kitbag_acu
tfa_kitbag_blk
tfa_kitbag_dou
tfa_kitbag_fol
tfa_kitbag_mcam
tfa_kitbag_nwu2
tfa_kitbag_tan
tfa_kitbag_wte
tfa_assault_blk
tfa_assault_fol
tfa_assault_mcam
tfa_assault_tan
rhsusf_assault_eagleaiii_ucp
rhsusf_assault_eagleaiii_ocp
rhsusf_assault_eagleaiii_coy


///////////////////////////////////////////////////////////////////////////////
// Headgear/goggles/etc
///////////////////////////////////////////////////////////////////////////////

FUTARM_HelmetB
FUTARM_Helmet_AT
FUTARM_Helmet_MED
FUTARM_Helmet_ENG
FUTARM_MilCap
FUTARM_Boonie
H_Cap_pmc
H_Cap_tan_pmc
H_Cap_pmc_headphones
H_Capbw_pmc
H_Capbw_tan_pmc
H_Booniehat_rgr
H_Booniehat_GCAMO
H_Booniehat_DMARPAT
H_HelmetB_plain_blk
H_PilotHelmetHeli_PMC
mich_bis_acu
mich_bis_dou
mich_bis_mcam
mich_bis_white
tfa_boon_acu
tfa_boon_bdu
tfa_boon_blk
tfa_boon_des
tfa_boon_dou
tfa_boon_grn
tfa_boon_khk
tfa_boon_mcam
tfa_boon_nwu2
tfa_boon_nwu3
tfa_boon_tiger
tfa_boon_tri
tfa_boon_usmc_des
tfa_boon_usmc_wdl
tfa_boon_white
tfa_cand_wht_co
tfa_cap_bears
tfa_cap_blk_co
tfa_cap_bro
tfa_cap_fry
tfa_cap_hs_blk
tfa_cap_hs_grn
tfa_cap_hs_tan
tfa_cap_lad
tfa_cap_mdf
tfa_cap_oak
tfa_cap_ten
tfa_cap_war
tfa_helmet_aor
tfa_helmet_black
tfa_helmet_dou
tfa_helmet_foliage
tfa_helmet_multi
tfa_helmet_nwu3
tfa_helmet_tan
tfa_mich_atac_au
tfa_mich_atac_fg
tfa_mich_bdu
tfa_mich_dec_easy5
tfa_mich_dec_george7
tfa_mich_dec_india5
tfa_mich_dec_item1
tfa_mich_dec_yankee18
tfa_mich_ghost_alpha3
tfa_mich_ghost_golf1
tfa_mich_ghost_hotel2
tfa_mich_grn
tfa_mich_kryptek_high
tfa_mich_kryptek_MAN
tfa_mich_kryptek_nom
tfa_mich_mcam
tfa_mich_tri
tfa_mich_usmc_des
tfa_mich_usmc_wdl
tfa_mich_aus_des
tfa_mich_aus_wdl
tfa_mich_bel_des
tfa_mich_bel_wdl
tfa_mich_can_des
tfa_mich_can_wdl
tfa_mich_den_des
tfa_mich_den_wdl
tfa_mich_fin_des
tfa_mich_fin_wdl
tfa_mich_fra_des
tfa_mich_fra_wdl
tfa_mich_ger_des
tfa_mich_ger_wdl
tfa_mich_ita_des
tfa_mich_ita_wdl
tfa_mich_jpn_des
tfa_mich_jpn_wdl
tfa_mich_ned_des
tfa_mich_ned_wdl
tfa_mich_nor_des
tfa_mich_nor_wdl
tfa_mich_pol_des
tfa_mich_pol_wdl
tfa_mich_swe_des
tfa_mich_swe_wdl
tfa_mich_uk_des
tfa_mich_uk_mtp
tfa_mich_uk_wdl
tfa_mich_us_des
tfa_mich_us_des2
tfa_mich_us_mcam
tfa_mich_us_tiger
tfa_mich_us_wood
rhs_fieldcap
rhs_fieldcap_digi
rhs_fieldcap_ml
rhs_fieldcap_helm
rhs_fieldcap_helm_digi
rhs_fieldcap_helm_ml
rhs_beanie
rhs_beanie_green
rhs_6b26
rhs_6b26_bala
rhs_6b26_ess
rhs_6b26_ess_bala
rhs_6b26_green
rhs_6b26_bala_green
rhs_6b26_ess_green
rhs_6b26_ess_bala_green
rhs_6b27m
rhs_6b27m_digi
rhs_6b27m_ml
rhs_6b27m_ess_bala
rhs_6b27m_digi_ess_bala
rhs_6b27m_ML_ess_bala
rhs_6b27m_bala
rhs_6b27m_digi_bala
rhs_6b27m_ml_bala
rhs_6b27m_ess
rhs_6b27m_digi_ess
rhs_6b27m_ml_ess
rhs_6b27m_green
rhs_6b27m_green_ess
rhs_6b27m_green_bala
rhs_6b27m_green_ess_bala
rhs_6b28
rhs_6b28_flora
rhs_6b28_ess
rhs_6b28_flora_ess
rhs_6b28_bala
rhs_6b28_flora_bala
rhs_6b28_ess_bala
rhs_6b28_flora_ess_bala
rhs_6b28_green
rhs_6b28_green_ess
rhs_6b28_green_bala
rhs_6b28_green_ess_bala
rhs_Booniehat_digi
rhs_Booniehat_flora
rhs_zsh7a
rhs_zsh7a_mike
rhs_gssh18
rhs_tsh4
rhs_tsh4_ess
rhs_tsh4_bala
rhs_tsh4_ess_bala
rhs_6b23
rhs_6b23_crew
rhs_6b23_engineer
rhs_6b23_medic
rhs_6b23_rifleman
rhs_6b23_crewofficer
rhs_6b23_sniper
rhs_6b23_6sh92
rhs_6b23_6sh92_vog
rhs_6b23_6sh92_vog_headset
rhs_6b23_6sh92_headset
rhs_6b23_6sh92_headset_mapcase
rhs_6b23_6sh92_radio
rhs_6sh46
rhs_vest_commander
rhs_6b23_digi
rhs_6b23_digi_crew
rhs_6b23_digi_engineer
rhs_6b23_digi_medic
rhs_6b23_digi_rifleman
rhs_6b23_digi_crewofficer
rhs_6b23_digi_sniper
rhs_6b23_digi_6sh92
rhs_6b23_digi_6sh92_vog
rhs_6b23_digi_6sh92_vog_headset
rhs_6b23_digi_6sh92_headset
rhs_6b23_digi_6sh92_headset_mapcase
rhs_6b23_digi_6sh92_radio
rhs_6b23_digi_6sh92_Spetsnaz
rhs_6b23_digi_6sh92_Vog_Radio_Spetsnaz
rhs_6b23_ML
rhs_6b23_ML_crew
rhs_6b23_ML_engineer
rhs_6b23_ML_medic
rhs_6b23_ML_rifleman
rhs_6b23_ML_crewofficer
rhs_6b23_ML_sniper
rhs_6b23_ML_6sh92
rhs_6b23_ML_6sh92_vog
rhs_6b23_ML_6sh92_vog_headset
rhs_6b23_ML_6sh92_headset
rhs_6b23_ML_6sh92_headset_mapcase
rhs_6b23_ML_6sh92_radio
rhs_vydra_3m
rhs_6b13
rhs_6b13_crewofficer
rhs_6b13_6sh92
rhs_6b13_6sh92_vog
rhs_6b13_6sh92_headset_mapcase
rhs_6b13_6sh92_radio
rhs_6b13_EMR
rhs_6b13_Flora
rhs_6b13_Flora_crewofficer
rhs_6b13_Flora_6sh92
rhs_6b13_Flora_6sh92_vog
rhs_6b13_Flora_6sh92_headset_mapcase
rhs_6b13_Flora_6sh92_radio
rhs_6sh92
rhs_6sh92_vog
rhs_6sh92_vog_headset
rhs_6sh92_headset
rhs_6sh92_radio
rhs_6sh92_digi
rhs_6sh92_digi_vog
rhs_6sh92_digi_vog_headset
rhs_6sh92_digi_headset
rhs_6sh92_digi_radio
rhsusf_patrolcap_ocp
rhsusf_patrolcap_ucp
rhs_Booniehat_ocp
rhs_Booniehat_ucp
rhs_Booniehat_marpatd
rhs_Booniehat_marpatwd
rhs_Booniehat_m81
rhsusf_ach_helmet_ocp
rhsusf_ach_helmet_ocp_norotos
rhsusf_ach_helmet_ucp
rhsusf_ach_helmet_ucp_norotos
rhsusf_ach_helmet_M81
rhsusf_ach_helmet_camo_ocp
rhsusf_ach_helmet_headset_ocp
rhsusf_ach_helmet_headset_ucp
rhsusf_ach_helmet_ESS_ocp
rhsusf_ach_helmet_ESS_ucp
rhsusf_ach_helmet_headset_ess_ocp
rhsusf_ach_helmet_headset_ess_ucp
rhsusf_ach_bare
rhsusf_ach_bare_ess
rhsusf_ach_bare_headset
rhsusf_ach_bare_headset_ess
rhsusf_ach_bare_tan
rhsusf_ach_bare_tan_ess
rhsusf_ach_bare_tan_headset
rhsusf_ach_bare_tan_headset_ess
rhsusf_ach_bare_wood
rhsusf_ach_bare_wood_ess
rhsusf_ach_bare_wood_headset
rhsusf_ach_bare_wood_headset_ess
rhsusf_ach_bare_des
rhsusf_ach_bare_des_ess
rhsusf_ach_bare_des_headset
rhsusf_ach_bare_des_headset_ess
rhsusf_ach_bare_semi
rhsusf_ach_bare_semi_ess
rhsusf_ach_bare_semi_headset
rhsusf_ach_bare_semi_headset_ess
rhsusf_opscore_01
rhsusf_opscore_01_tan
rhsusf_opscore_02
rhsusf_opscore_02_tan
rhsusf_opscore_03_ocp
rhsusf_opscore_04_ocp
rhsusf_cvc_helmet
rhsusf_cvc_green_helmet
rhsusf_cvc_ess
rhsusf_cvc_green_ess
rhsusf_hgu56p
rhsusf_hgu56p_mask
rhsusf_mich_helmet_marpatwd
rhsusf_mich_helmet_marpatwd_headset
rhsusf_mich_helmet_marpatd
rhsusf_mich_helmet_marpatd_headset
rhsusf_mich_helmet_marpatwd_alt
rhsusf_mich_helmet_marpatwd_alt_headset
rhsusf_mich_helmet_marpatd_alt
rhsusf_mich_helmet_marpatd_alt_headset
rhsusf_mich_helmet_marpatwd_norotos
rhsusf_mich_helmet_marpatwd_norotos_headset
rhsusf_mich_helmet_marpatd_norotos
rhsusf_mich_helmet_marpatd_norotos_headset
rhsusf_mich_helmet_marpatwd_norotos_arc
rhsusf_mich_helmet_marpatwd_norotos_arc_headset
rhsusf_mich_helmet_marpatd_norotos_arc
rhsusf_mich_helmet_marpatd_norotos_arc_headset
rhsusf_mich_bare
rhsusf_mich_bare_headset
rhsusf_mich_bare_alt
rhsusf_mich_bare_norotos
rhsusf_mich_bare_norotos_headset
rhsusf_mich_bare_norotos_alt
rhsusf_mich_bare_norotos_alt_headset
rhsusf_mich_bare_norotos_arc
rhsusf_mich_bare_norotos_arc_headset
rhsusf_mich_bare_norotos_arc_alt
rhsusf_mich_bare_norotos_arc_alt_headset
rhsusf_mich_bare_tan
rhsusf_mich_bare_tan_headset
rhsusf_mich_bare_alt_tan
rhsusf_mich_bare_norotos_tan
rhsusf_mich_bare_norotos_tan_headset
rhsusf_mich_bare_norotos_alt_tan
rhsusf_mich_bare_norotos_alt_tan_headset
rhsusf_mich_bare_norotos_arc_tan
rhsusf_mich_bare_norotos_arc_tan_headset
rhsusf_mich_bare_norotos_arc_alt_tan
rhsusf_mich_bare_norotos_arc_alt_tan_headset
rhsusf_mich_bare_semi
rhsusf_mich_bare_semi_headset
rhsusf_mich_bare_alt_semi
rhsusf_mich_bare_norotos_semi
rhsusf_mich_bare_norotos_semi_headset
rhsusf_mich_bare_norotos_alt_semi
rhsusf_mich_bare_norotos_alt_semi_headset
rhsusf_mich_bare_norotos_arc_semi
rhsusf_mich_bare_norotos_arc_semi_headset
rhsusf_mich_bare_norotos_arc_alt_semi
rhsusf_mich_bare_norotos_arc_alt_semi_headset
rhsusf_lwh_helmet_marpatd
rhsusf_lwh_helmet_marpatd_ess
rhsusf_lwh_helmet_marpatd_headset
rhsusf_lwh_helmet_marpatwd
rhsusf_lwh_helmet_marpatwd_ess
rhsusf_lwh_helmet_marpatwd_headset
rhsusf_lwh_helmet_M1942
rhsusf_Bowman
rhsusf_bowman_cap


///////////////////////////////////////////////////////////////////////////////
// Vests
///////////////////////////////////////////////////////////////////////////////

FUTARM_PlateCarrier1_rgr
FUTARM_PlateCarrier_AT
FUTARM_PlateCarrier_MED
FUTARM_PlateCarrier_ENG
FUTARM_PlateCarrier_GL
FUTARM_Rangemaster
V_PlateCarrier1_PMC_rgr
V_PlateCarrier1_PMC_blk
V_PlateCarrier1_PMC_marpat
V_PlateCarrier1_PMC_khki
V_PlateCarrierInd_PMC_blk
V_PlateCarrierInd_PMC_grn
V_TacVest_darkblck
tfa_acu_vest_co
tfa_black_vest_co
tfa_blk_vest_co
tfa_cand_vest_co
tfa_dou_vest_co
tfa_fol_vest_co
tfa_grn_vest_co
tfa_mcam_vest_co
tfa_nwu2_vest_co
tfa_rgrn_vest_co
tfa_tan_grn_vest_co
tfa_tan_vest_co
tfa_white_vest_co
tfa_wte_vest_co
tfax_blk_vest
tfax_fol_vest
tfax_grn_vest
tfax_mcam_vest
tfax_tan_vest
tfax_vest_ger_des
tfax_vest_ger_wdl
rhs_6sh92
rhs_6sh92_radio
rhs_6sh92_vog
rhs_6sh92_vog_headset
rhs_6sh92_headset
rhs_6sh92_digi
rhs_6sh92_digi_radio
rhs_6sh92_digi_vog
rhs_6sh92_digi_vog_headset
rhs_6sh92_digi_headset
rhs_6b23
rhs_6b23_crew
rhs_6b23_crewofficer
rhs_6b23_engineer
rhs_6b23_medic
rhs_6b23_rifleman
rhs_6b23_sniper
rhs_6b23_6sh92
rhs_6b23_6sh92_radio
rhs_6b23_6sh92_vog
rhs_6b23_6sh92_vog_headset
rhs_6b23_6sh92_headset
rhs_6b23_6sh92_headset_mapcase
rhs_6b23_digi
rhs_6b23_digi_crew
rhs_6b23_digi_crewofficer
rhs_6b23_digi_engineer
rhs_6b23_digi_medic
rhs_6b23_digi_rifleman
rhs_6b23_digi_sniper
rhs_6b23_digi_6sh92
rhs_6b23_digi_6sh92_radio
rhs_6b23_digi_6sh92_vog
rhs_6b23_digi_6sh92_vog_headset
rhs_6b23_digi_6sh92_headset
rhs_6b23_digi_6sh92_headset_mapcase
rhs_6b23_ML
rhs_6b23_ML_crew
rhs_6b23_ML_crewofficer
rhs_6b23_ML_engineer
rhs_6b23_ML_medic
rhs_6b23_ML_rifleman
rhs_6b23_ML_sniper
rhs_6b23_ML_6sh92
rhs_6b23_ML_6sh92_radio
rhs_6b23_ML_6sh92_vog
rhs_6b23_ML_6sh92_vog_headset
rhs_6b23_ML_6sh92_headset
rhs_6b23_ML_6sh92_headset_mapcase
rhs_6sh46
rhs_vest_commander
rhs_vydra_3m
rhsusf_iotv_ucp
rhsusf_iotv_ucp_grenadier
rhsusf_iotv_ucp_medic
rhsusf_iotv_ucp_repair
rhsusf_iotv_ucp_rifleman
rhsusf_iotv_ucp_SAW
rhsusf_iotv_ucp_squadleader
rhsusf_iotv_ucp_teamleader
rhsusf_iotv_ocp
rhsusf_iotv_ocp_grenadier
rhsusf_iotv_ocp_medic
rhsusf_iotv_ocp_repair
rhsusf_iotv_ocp_rifleman
rhsusf_iotv_ocp_SAW
rhsusf_iotv_ocp_squadleader
rhsusf_iotv_ocp_teamleader
rhsusf_spc
rhsusf_spc_rifleman
rhsusf_spc_iar
rhsusf_spc_corpsman
rhsusf_spc_crewman
rhsusf_spc_light
rhsusf_spc_marksman
rhsusf_spc_mg
rhsusf_spc_squadleader
rhsusf_spc_teamleader
rhsusf_spcs_ocp
rhsusf_spcs_ucp


///////////////////////////////////////////////////////////////////////////////
// Vehicles
///////////////////////////////////////////////////////////////////////////////
//Merlins
GR_AW101_1
//Armed
GR_AW101_2

//Hueys
GR_UH1D_1
GR_UH1H_3
GR_UH1H_4
GR_UH1H_6
GR_UH1N_1
GR_UH1N_2
//Armed
GR_UH1H_2
GR_UH60_1

//Mi
GR_Mi8_1
//Armed
GR_Mi_171_2

//Bell
GR_Bell412_3
GR_Bell412_2
GR_Bell412_1

RHS_UH60M_MEV
RHS_UH60M_MEV_d
RHS_UH1Y_UNARMED
RHS_UH1Y_UNARMED_d
RHS_CH_47F1
RHS_CH_47F_light
RHS_UH60M
RHS_Mi8amt_civilian


rhsusf_m113d_usarmy_unarmed
rhsusf_m113_usarmy_unarmed

rhsusf_m1025_w_s_m2
rhsusf_m1025_d
rhsusf_m1025_w
rhsusf_m998_w_2dr
rhsusf_m998_w_s_2dr
rhsusf_m988_d_s_2dr
rhsusf_m988_w_2dr_halftop
rhs_tigr_vdv
rhs_tigr_vmf
rhs_tigr_msv
rhs_tigr_vv
rhs_tigr_3camo_vdv
rhs_tigr_3camo_vmf
rhs_tigr_3camo_msv
rhs_tigr_3camo_vv
rhs_tigr_ffv_vdv
rhs_tigr_ffv_vmf
rhs_tigr_ffv_msv
rhs_tigr_ffv_vv
rhs_tigr_ffv_3camo_vdv
rhs_tigr_ffv_3camo_vv
rhsusf_M1078A1P2_B_M2_wd_fmtv_usarmy
rhsusf_M1078A1P2_B_M2_wd_open_fmtv_usarmy
rhsusf_M1078A1P2_B_M2_wd_flatbed_fmtv_usarmy
rhsusf_M1078A1P2_B_M2_d_fmtv_usarmy
rhsusf_M1078A1P2_B_M2_d_open_fmtv_usarmy
rhsusf_M1078A1P2_B_M2_d_flatbed_fmtv_usarmy
rhsusf_m998_w_2dr_fulltop
rhsusf_m998_d_2dr_fulltop
rhsusf_m998_w_s_2dr_fulltop
rhsusf_m998_d_s_2dr_fulltop
rhs_uaz_open_MSV_01
RHS_UAZ_MSrV_01
RHS_Ural_Flat_MSV_01
RHS_Ural_Fuel_VDV_01
